"use client";

import { useState } from "react";
import { AuthCard } from "@/components/auth/auth-card";
import { PinInput } from "@/components/auth/pin-input";
import { Button } from "@/components/ui/button";
import { ShieldAlert } from "lucide-react";
import { useRouter } from "next/navigation";
import Link from "next/link";

export default function MfaChallengePage() {
  const router = useRouter();
  const [code, setCode] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    if (code.length !== 6) {
      setError("Please input the 6-digit TOTP verification code.");
      return;
    }

    setLoading(true);
    setError(null);
    await new Promise((resolve) => setTimeout(resolve, 800));

    // Successful MFA challenge -> go to dashboard
    router.push("/dashboard");
  };

  return (
    <AuthCard
      title="Multi-Factor Challenge"
      description="Enter the 6-digit code generated by your authenticator app to complete sign in."
      footer={
        <div className="text-center">
          <Link
            href="/login"
            className="text-xs text-text-secondary hover:text-text-primary transition-colors"
          >
            Sign in with a different account
          </Link>
        </div>
      }
    >
      <div className="flex flex-col items-center justify-center space-y-5">
        <div className="flex h-12 w-12 items-center justify-center rounded-full bg-accent/20 border border-accent/40 text-on-accent">
          <ShieldAlert size={22} />
        </div>

        <form onSubmit={handleVerify} className="w-full space-y-4">
          <PinInput
            length={6}
            value={code}
            onChange={(val) => {
              setCode(val);
              if (error) setError(null);
            }}
            error={!!error}
          />

          {error && <p className="text-center text-xs text-danger">{error}</p>}

          <Button
            type="submit"
            variant="accent"
            className="w-full mt-2"
            disabled={code.length !== 6}
            isLoading={loading}
          >
            Authenticate Session
          </Button>
        </form>
      </div>
    </AuthCard>
  );
}
